name: Generate snake animation

on:
  schedule: # every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Generate light snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/snake.svg

      - name: Generate dark snake SVG (github-dark palette)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/snake-dark.svg?palette=github-dark

      - name: Commit & push generated files to 'output' branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore(snk): update snake images"
          add: "output/**"
          branch: output
